### ISSUE TITLE
Design in-html representation of link to Presentation resource

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#20]
e.g. RDFa, JSON-LD or microdata syntax within HTML to link from any web page to a Manifest or Collection that is related to the page. Clients can then follow the link and display the resource in a IIIF viewer.

See: https://groups.google.com/d/msg/iiif-discuss/JrmXLcfvWfk/6KfYrDiHJLAJ 
And: https://developers.google.com/custom-search/docs/structured_data?hl=en

From IIIF/api#557

**Comment by tomcrane** [comment]
If JSON-LD is preferred, how similar does this look to the JSON-LD in IIIF/discovery#19?

**Comment by acdha** [comment]
I think I mentioned this somewhere after the Slack conversation but e.g. https://www.wdl.org/en/item/123/ has a link tag specifying the profile like this:

```
<link rel="alternate" type="application/ld+json;profile=&quot;http://iiif.io/api/presentation/2/context.json&quot;" href="https://www.wdl.org/en/item/123/manifest">
```

That might be a reasonably standard way to do this.

**Comment by tomcrane** [comment]
Although I gave it the label `content-state`, this issue is about a link from a web page to the IIIF resource itself (e.g., for machines or browser plugins to follow, from an object's descriptive metadata page) rather than a link to initialise a viewer with a particular focus.

This is clearly related to the concerns of the current draft of the content state, but does it belong there? I think so (rather there than anywhere else). In the issue linked above (https://github.com/2SC1815J/open-in-iiif-viewer/issues/1#issuecomment-396978788) pattern 1 is content-state-like, pattern 2 requires no new patterns, just agreement that this is how it is done (section with example in content state spec).

This issue is about linking to data, rather than linking to a user experience.

**Comment by azaroth42** [comment]
Is it just the content-state API with no features, other than the reference to the manifest? 

At which point, is this already solved here: https://iiif.io/api/content-state/0.2/#initialization-mechanisms-link

If so, close, fixed? :)

**Comment by azaroth42** [comment]
This issue has two separate concerns -- the initialization of a viewer per the content state spec from data in a page, which is solved by the content state api already. However there's also IIIF/api#2212, which is focused on clients that read structured data as their input, and they also need to be able to find links to the presentation API resources and a better description of the issue.

Closing in favor of IIIF/api#2212.
