### ISSUE TITLE
Replace orderedItems by something type-specific?

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#27]
_Warning: this is a comment that's maybe better to address for future versions of the spec, post Washington, not now!_

Section 3.3 of http://preview.iiif.io/api/discovery/api/discovery/0.1/ specifies “Activities must have the object property. The value must be a JSON object, with the id and type properties. “

One of the reasons for which the Discovery API pages are currently quite verbose is because we have to specify the type of the IIIF resource being the object of an Activity (e.g. Manifest), even though there might not be any other statement about that object. Considering that most of the time the resources on a page will be of one type, could we materialize the type into the property that contains the list of activities (e.g. to orderedManifestActivities), so that we save some complexity for the simplest cases?
This is especially interesting if as per the issues on additional properties and content indexing (#8, #12, #24) we decide to limit the number of manifest properties referenced in the Discovery API.

**Comment by azaroth42** [comment]
:-1:  We tried this in Presentation 2.0/2.1 and regretted it later when there were different types of resource ordered in the same list.  For example we had to get rid of `ranges` and `canvases` off of Range, and replace with `members` (and in 3.0 renamed to `items` for consistency).

Also, the type forces the JSON Object construction rather than compacting the object to just the URI as a string.  This is one of the (recently enumerated) design principles around JSON-LD:  http://iiif.io/api/annex/notes/design_patterns/#use-json-objects-for-referenced-resources 

The verbosity is a price of doing business with JSON-LD, I'm afraid.  The plus side is that it compresses well :D

**Comment by aisaac** [comment]
OK I accept the point!
Maybe we shouldn't close the issue right now though, and flag it to the group? Others may have the same question, unless the discussion in the Presentation API was very visible. I don't remember it - maybe because it felt very natural to do it the way it is done now ;-)

**Comment by azaroth42** [comment]
Propose to discuss proposal to close on 2018-07-11 call

**Comment by aisaac** [comment]
2018-07-11 call: we agree that there could be activities about other types of resources than manifests therefore it seems wise to hardcode the type the list at the property level.
