### ISSUE TITLE
Trigger full refresh from level 0?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#33]
From the discussion at the Washington conference:

> Is there a way to tell harvester to trigger a complete refresh?

This would be very useful for "level 0" implementations that don't track anything more than current state.

**Comment by azaroth42** [comment]
The scenario:  If the level 0 implementation rebuilds nightly without any knowledge of the previous state (which is very likely), then the consumer might think that it needs to recrawl every referenced resource every day. However the state might be 100% identical to the previous day, especially over a holiday or weekend. Having some way to say that a significant change has occurred within the dataset seems valuable, perhaps as a manually set `updated` date in the Collection document.

**Comment by zimeon** [comment]
It as rather an edge-case that an implementation would be able to generate a useful `updated` date for a collection but would not be able to support level 1 (which should be strongly recommended). Generation of a useful `updated` date would usually need to be based on understanding of the update time for each underlying resource which would mean [level 1](https://preview.iiif.io/api/discovery/api/discovery/0.1/#level-1-basic-change-list) could be supported (`endTime` for each resource).

Expected behavior of harvesters encountering level 0 resource lists will be to periodically re-harvest/check (perhaps weekly).

Consensus on 2018-08-08 call, close `wontfix`.
