### ISSUE TITLE
What properties from IIIF should be in the activity?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#8]
The activity MUST reference the IIIF resource that changed, but other than the URI which properties are useful to machines to process for discovery purposes?

- [X] `id` as it's needed to download the resource!
- [X] `type` as a very easy way to filter different types to different workflows in a merged stream of (eg #5) Collections and Manifests
- [ ] `seeAlso` to avoid downloading the resource at all?
- [ ] `label`, `summary` (#6) and `metadata` as the core content to index??
- [ ] `thumbnail` to present to the user?

Are there any others that would be useful?

**Comment by azaroth42** [comment]
My proposal would be to add `seeAlso` as a way to encourage the best practice of making machine readable metadata available in a consistent way. Adding the raw content and the presentational aspects to the activity seem like they bloat out the stream unnecessarily, and this is why the crawler would download the iiif resource.

So yes to checking `seeAlso` no to the others in the issue.

**Comment by zimeon** [comment]
I think it should _either_ be @azaroth42's https://github.com/IIIF/discovery/issues/8#issuecomment-351490232 (just `seeAlso`) or nothing beyond `id` and `type`. Rationales:

  * pro `type` because it supports selective harvesting (the others don't)
  * `seeAlso`
    * pro: it might efficiently support a key use-case of indexing IIIF resources based on structured metadata and not the IIIF presentation information (avoiding need to download IIIF resource)
    * con: does the target of `seeAlso` change in lockstep with the IIIF resource? There MUST be an activity in the stream if the target changes, even if the IIIF resource doesn't -- thus the semantics are a bit iffy. Ideally one would have updates both for the IIIF resources and the `seeAlso` target resources, and an indexer would have to be smart enough to follow both and work out what matters based on their indexing strategy
  * con `label`,  `summary`, `metadata`, `thumbnail`, anything else -- are there really cases where this is all the information that would be needed, thus obviating the need to download resource. I suspect not and thus the info would just be bloat (and introduce questions of what to do in case of mismatch)

**Comment by mixterj** [comment]
I  think we should be careful about caching too much in the AS. I agree that `id` and `type` should be included but outside of that I am not sure how much value we gain. Adding metadata would add the overhead of keeping both the Manifest and AS up-to-date. Anything that is a string from the Manifest introduces issues of what languages should be grabbed (all, just English, based on the location of the organization). All that leads to more keeping things up-to-date as well as uniformity issues.

I do think the `seeAlso` URI could be helpful but only if it could reliably deliver back standard formats of metadata. Otherwise we would be pushing IIIF Manifest parsing logic into the AS parsing logic.

Finally, from a linked data perspective I do not think we need 'thumbnail'. Just follow the links :)

**Comment by mattmcgrattan** [comment]
Seconding @zimeon 's comments re: the pros and cons of seeAlso. 

Would we expect that the AS stream would contain Update events on manifests where the manifest was unchanged but resources linked from the manifest (e.g. seeAlso, but also, say, otherContent) had changed?

**Comment by azaroth42** [comment]
From slack,  @sdellis:

I'm sorry I won't be able to attend the call, but in addition to resource list item objects containing 1) the Resource type 2) the Resource URI, I think the version of the Presentation API should be included. It would help viewers determine whether or not they'd be able to render the resource, or in this use case, which viewers to offer users to choose from: https://github.com/IIIF/iiif-stories/issues/99

**Comment by aisaac** [comment]
I'm in agreement that we should reduce redundancy and thus limit the number of properties that are also in the manifest. Besides, in the current draft the rationale behind adding some of these properties refers to the "end-user of a discovery system". I'm not sure this is strongly backed by our use cases.

Re. `seeAlso`, I'm in favour of having it, but I think I'm biased because I'm looking at metadata aggregation scenarios of obvious use to Europeana. In fact it would imply that we're moving from a solution for crawling IIIF resources to a solution for crawling IIIF resources *and* metadata. Or at least it would force us to consider our position with respect to this issue. Especially to think of the deeper semantic issue of what counts as an 'update' as @zimeon noted.
This may be a useful step towards answering some of the other parts of our group's charter, but it's perhaps premature to include them in the first version of a crawling spec.
Maybe we can add it for now, but with a big fat editor note that we would revisit it in the light of the group's future work - and that we especially would welcome feedback on it in the meanwhile.

**Comment by glenrobson** [comment]
Would adding a context to the IIIF resource solve the version issue? Would that conflict with the AS stuff?

**Comment by azaroth42** [comment]
Consensus on call of 2018-02-07 is to put seeAlso into the `defer`ed issue #12 as to how to get easy access to the content, to leave out everything else by `id` and `type`.

In general, we are looking for implementation feedback at this stage to help inform how to optimize harvesters to do their job.  Version, seeAlso, and so forth are optimizations that we don't know whether they're useful or not at this stage.

**Comment by azaroth42** [comment]
For `@context` as a version signal, one of the advantages of JSON-LD 1.1 is the ability to scope contexts such that they only apply at certain levels. This means that we can take the contexts out of the data (which can't be put there by framing anyway, one of our JSON-LD 1.0 headaches around extensions) and hidden behind a single master context. 

It also would conflict with AS context, such as the label and summary properties.

**Comment by azaroth42** [comment]
Closing, done (only id and type) in version for IIIF site.
